#include "structs.h"
#include <string>
#include <iostream>
using namespace std;

int main()
{
	/*recuperarCatPregResp(unaListaCat);

	ListaCategoria* unaListaCat = new ListaCategoria();
	iniciarCategoriasPreguntasRespuestas(unaListaCat);
	*/

	//ListaCategoria *listaCategoria = new listaCategoria();
	
	/*ListaCategorias* iniciar;
	iniciar = iniciarCategoriasPreguntasRespuestas();*/
	
	FILE* archivoContenido = fopen("contenido.dat", "wb");

	Juego* unJuego = new Juego();
	
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "?Como se llamo la bomba lanzada en la ciudad de Hiroshima el 6 de Agosto de 1945?");
	strcpy(unJuego->descripcionRespuesta, "1. Fat Man");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "?Como se llamo la bomba lanzada en la ciudad de Hiroshima el 6 de Agosto de 1945?");
	strcpy(unJuego->descripcionRespuesta, "2. Little Boy");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Como se llamo la bomba lanzada en la ciudad de Hiroshima el 6 de Agosto de 1945?");
	strcpy(unJuego->descripcionRespuesta, "3. Enola Gay");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Como se llamo la bomba lanzada en la ciudad de Hiroshima el 6 de Agosto de 1945?");
	strcpy(unJuego->descripcionRespuesta, "4. Luftwaffe");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "?En que anio se desarrollo la guerra de Malvinas?");
	strcpy(unJuego->descripcionRespuesta, "1. 1980");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "?En que anio se desarrollo la guerra de Malvinas?");
	strcpy(unJuego->descripcionRespuesta, "2. 1982");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿En que anio se desarrollo la guerra de Malvinas?");
	strcpy(unJuego->descripcionRespuesta, "3. 1979");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿En que anio se desarrollo la guerra de Malvinas?");
	strcpy(unJuego->descripcionRespuesta, "4. 1983");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Cuál fue la capital del Imperio Inca?");
	strcpy(unJuego->descripcionRespuesta, "1. Cuzco");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Cuál fue la capital del Imperio Inca?");
	strcpy(unJuego->descripcionRespuesta, "2. Quito");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Cuál fue la capital del Imperio Inca?");
	strcpy(unJuego->descripcionRespuesta, "3. La Paz");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Cuál fue la capital del Imperio Inca?");
	strcpy(unJuego->descripcionRespuesta, "4. Lima");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Quién fue la primera persona en pisar la luna?");
	strcpy(unJuego->descripcionRespuesta, "1. Neil Armstrong");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Quién fue la primera persona en pisar la luna?");
	strcpy(unJuego->descripcionRespuesta, "2. David Scott");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Quién fue la primera persona en pisar la luna?");
	strcpy(unJuego->descripcionRespuesta, "3. John Young");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Quién fue la primera persona en pisar la luna?");
	strcpy(unJuego->descripcionRespuesta, "4. James Irwin");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Cómo se llama la máquina que utilizaban los alemanes para encriptar sus mensajes y que los aliados no supieran que decían?");
	strcpy(unJuego->descripcionRespuesta, "1. Neil Armstrong");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Cómo se llama la máquina que utilizaban los alemanes para encriptar sus mensajes y que los aliados no supieran que decían?");
	strcpy(unJuego->descripcionRespuesta, "2. David Scott");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Cómo se llama la máquina que utilizaban los alemanes para encriptar sus mensajes y que los aliados no supieran que decían?");
	strcpy(unJuego->descripcionRespuesta, "3. John Young");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Cómo se llama la máquina que utilizaban los alemanes para encriptar sus mensajes y que los aliados no supieran que decían?");
	strcpy(unJuego->descripcionRespuesta, "4. James Irwin");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Quién fue la primera persona en pisar la luna?");
	strcpy(unJuego->descripcionRespuesta, "1. Neil Armstrong");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Quién fue la primera persona en pisar la luna?");
	strcpy(unJuego->descripcionRespuesta, "2. David Scott");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Quién fue la primera persona en pisar la luna?");
	strcpy(unJuego->descripcionRespuesta, "3. John Young");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Historia");
	strcpy(unJuego->descripcionPregunta, "¿Quién fue la primera persona en pisar la luna?");
	strcpy(unJuego->descripcionRespuesta, "4. James Irwin");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 1;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "?En que frontera se encuentra el Monte Everest?");
	strcpy(unJuego->descripcionRespuesta, "1. Nepal e India");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "?En que frontera se encuentra el Monte Everest?");
	strcpy(unJuego->descripcionRespuesta, "2. China y Nepal");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "?En que frontera se encuentra el Monte Everest?");
	strcpy(unJuego->descripcionRespuesta, "3. China e India");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "?En que frontera se encuentra el Monte Everest?");
	strcpy(unJuego->descripcionRespuesta, "4. China y Rusia");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "?Cual es el rio mas grande?");
	strcpy(unJuego->descripcionRespuesta, "1. Rio Nilo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "?Cual es el rio mas grande?");
	strcpy(unJuego->descripcionRespuesta, "2. Rio Amazonas");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "?Cual es el rio mas grande?");
	strcpy(unJuego->descripcionRespuesta, "3. Rio Amarillo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "?Cual es el rio mas grande?");
	strcpy(unJuego->descripcionRespuesta, "4. Rio Congo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Donde se encuentra el Gran Canion?");
	strcpy(unJuego->descripcionRespuesta, "1. Mexico");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Donde se encuentra el Gran Canion?");
	strcpy(unJuego->descripcionRespuesta, "2. Canada");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Donde se encuentra el Gran Canion?");
	strcpy(unJuego->descripcionRespuesta, "3. Estados Unidos");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Donde se encuentra el Gran Canion?");
	strcpy(unJuego->descripcionRespuesta, "4. Colombia");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Cual es el desierto calido mas grande?");
	strcpy(unJuego->descripcionRespuesta, "1. Atacama");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Cual es el desierto calido mas grande?");
	strcpy(unJuego->descripcionRespuesta, "2. Gran Desierto Arenoso");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Cual es el desierto calido mas grande?");
	strcpy(unJuego->descripcionRespuesta, "3. Sahara");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Cual es el desierto calido mas grande?");
	strcpy(unJuego->descripcionRespuesta, "4. Antartico");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Cual de estos paises es baniado unicamente por un oceano?");
	strcpy(unJuego->descripcionRespuesta, "1. Gran Bretania");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Cual de estos paises es baniado unicamente por un oceano?");
	strcpy(unJuego->descripcionRespuesta, "2. Canada");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Cual de estos paises es baniado unicamente por un oceano?");
	strcpy(unJuego->descripcionRespuesta, "3. Rusia");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Cual de estos paises es baniado unicamente por un oceano?");
	strcpy(unJuego->descripcionRespuesta, "4. Mexico");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Que pais es el segundo mas grande en terminos de poblacion?");
	strcpy(unJuego->descripcionRespuesta, "1. China");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Que pais es el segundo mas grande en terminos de poblacion?");
	strcpy(unJuego->descripcionRespuesta, "2. Rusia");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Que pais es el segundo mas grande en terminos de poblacion?");
	strcpy(unJuego->descripcionRespuesta, "3. India");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Geografia");
	strcpy(unJuego->descripcionPregunta, "Que pais es el segundo mas grande en terminos de poblacion?");
	strcpy(unJuego->descripcionRespuesta, "4. Indonesia");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 2;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Quien se corono campeon en el mundial de futbol en Alemania 2006?");
	strcpy(unJuego->descripcionRespuesta, "1. Brasil");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Quien se corono campeon en el mundial de futbol en Alemania 2006?");
	strcpy(unJuego->descripcionRespuesta, "2. Alemania");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Quien se corono campeon en el mundial de futbol en Alemania 2006?");
	strcpy(unJuego->descripcionRespuesta, "3. Italia");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Quien se corono campeon en el mundial de futbol en Alemania 2006?");
	strcpy(unJuego->descripcionRespuesta, "4. Francia");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cuantos titulos del campeonato de Wimbledon ha conseguido Roger Federer?");
	strcpy(unJuego->descripcionRespuesta, "1. 8");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cuantos titulos del campeonato de Wimbledon ha conseguido Roger Federer?");
	strcpy(unJuego->descripcionRespuesta, "2. 10");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cuantos titulos del campeonato de Wimbledon ha conseguido Roger Federer?");
	strcpy(unJuego->descripcionRespuesta, "3. 1");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cuantos titulos del campeonato de Wimbledon ha conseguido Roger Federer?");
	strcpy(unJuego->descripcionRespuesta, "4. 14");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual de estos deportes no es olimpico?");
	strcpy(unJuego->descripcionRespuesta, "1. Boxeo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual de estos deportes no es olimpico?");
	strcpy(unJuego->descripcionRespuesta, "2. Futbol playa");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual de estos deportes no es olimpico?");
	strcpy(unJuego->descripcionRespuesta, "3. Waterpolo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual de estos deportes no es olimpico?");
	strcpy(unJuego->descripcionRespuesta, "4. Golf");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "En cual de estos equipos no ha jugado Cristiano Ronaldo?");
	strcpy(unJuego->descripcionRespuesta, "1. Real Madrid");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "En cual de estos equipos no ha jugado Cristiano Ronaldo?");
	strcpy(unJuego->descripcionRespuesta, "2. Manchester United");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "En cual de estos equipos no ha jugado Cristiano Ronaldo?");
	strcpy(unJuego->descripcionRespuesta, "3. Sporting de Lisboa");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "En cual de estos equipos no ha jugado Cristiano Ronaldo?");
	strcpy(unJuego->descripcionRespuesta, "4. Inter de Milan");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cuanto dura un partido de basquet?");
	strcpy(unJuego->descripcionRespuesta, "1. 40 minutos");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cuanto dura un partido de basquet?");
	strcpy(unJuego->descripcionRespuesta, "2. Una hora");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cuanto dura un partido de basquet?");
	strcpy(unJuego->descripcionRespuesta, "3. 30 minutos");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cuanto dura un partido de basquet?");
	strcpy(unJuego->descripcionRespuesta, "4. 48 minutos");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "1. River Plate");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "2. Flamengo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "3. Gremio");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "4. Boca Juniors");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "1. River Plate");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "2. Flamengo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "3. Gremio");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "4. Boca Juniors");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "1. River Plate");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "2. Flamengo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "3. Gremio");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "4. Boca Juniors");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "1. River Plate");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "2. Flamengo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "3. Gremio");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "4. Boca Juniors");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "1. River Plate");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "2. Flamengo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "3. Gremio");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "4. Boca Juniors");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "1. River Plate");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "2. Flamengo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "3. Gremio");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	strcpy(unJuego->descripcionPregunta, "Cual es el actual campeon de la Copa LIbertadores de America?");
	strcpy(unJuego->descripcionRespuesta, "4. Boca Juniors");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 3;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En cual museo se encuentra el cuadro de la Mona Lisa?");
	strcpy(unJuego->descripcionRespuesta, "1. Museo del Prado");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En cual museo se encuentra el cuadro de la Mona Lisa?");
	strcpy(unJuego->descripcionRespuesta, "2. British Museum");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En cual museo se encuentra el cuadro de la Mona Lisa?");
	strcpy(unJuego->descripcionRespuesta, "3. Louvre");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En cual museo se encuentra el cuadro de la Mona Lisa?");
	strcpy(unJuego->descripcionRespuesta, "4. No se encuentra en ningun museo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En que anio nacio Van Gogh?");
	strcpy(unJuego->descripcionRespuesta, "1. 1853");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En que anio nacio Van Gogh?");
	strcpy(unJuego->descripcionRespuesta, "2. 1855");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En que anio nacio Van Gogh?");
	strcpy(unJuego->descripcionRespuesta, "3. 1800");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En que anio nacio Van Gogh?");
	strcpy(unJuego->descripcionRespuesta, "4. 1875");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Por que un director de orquesta necesita una batuta?");
	strcpy(unJuego->descripcionRespuesta, "1. Para mantener un orden en la orquesta");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En cual museo se encuentra el cuadro de la Mona Lisa?");
	strcpy(unJuego->descripcionRespuesta, "2. Para que todos los movimientos de su mano sean vistos por todos los musicos");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En cual museo se encuentra el cuadro de la Mona Lisa?");
	strcpy(unJuego->descripcionRespuesta, "3. Para guiar a todos los musicos");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "En cual museo se encuentra el cuadro de la Mona Lisa?");
	strcpy(unJuego->descripcionRespuesta, "4. Para que los musicos sepan que notas vienen");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Quien realizo la escultura Piedad del Vaticano?");
	strcpy(unJuego->descripcionRespuesta, "1. Bernini");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Quien realizo la escultura Piedad del Vaticano?");
	strcpy(unJuego->descripcionRespuesta, "2. Miguel Angel");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Quien realizo la escultura Piedad del Vaticano?");
	strcpy(unJuego->descripcionRespuesta, "3. Donatello");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Quien realizo la escultura Piedad del Vaticano?");
	strcpy(unJuego->descripcionRespuesta, "4. Laszlo Toth");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Cual de estas no es una de las 7 maravillas del mundo antiguo?");
	strcpy(unJuego->descripcionRespuesta, "1. Gran Piramide de Guiza");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Cual de estas no es una de las 7 maravillas del mundo antiguo?");
	strcpy(unJuego->descripcionRespuesta, "2. Templo de Artemisa");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Cual de estas no es una de las 7 maravillas del mundo antiguo?");
	strcpy(unJuego->descripcionRespuesta, "3. Faro de Alejandria");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Cual de estas no es una de las 7 maravillas del mundo antiguo?");
	strcpy(unJuego->descripcionRespuesta, "4. Partenon");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Cuando se inicio la construccion del Palacio de Versalles?");
	strcpy(unJuego->descripcionRespuesta, "1. 1623");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Cuando se inicio la construccion del Palacio de Versalles?");
	strcpy(unJuego->descripcionRespuesta, "2. 1590");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Cuando se inicio la construccion del Palacio de Versalles?");
	strcpy(unJuego->descripcionRespuesta, "3. 1622");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	strcpy(unJuego->descripcionPregunta, "Cuando se inicio la construccion del Palacio de Versalles?");
	strcpy(unJuego->descripcionRespuesta, "4. 1650");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 4;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Como se llama el proceso por el cual una celula se divide para formar dos celulas hijas?");
	strcpy(unJuego->descripcionRespuesta, "1. Segregacion");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Como se llama el proceso por el cual una celula se divide para formar dos celulas hijas?");
	strcpy(unJuego->descripcionRespuesta, "2. Mitosis");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Como se llama el proceso por el cual una celula se divide para formar dos celulas hijas?");
	strcpy(unJuego->descripcionRespuesta, "3. Meiosis");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Como se llama el proceso por el cual una celula se divide para formar dos celulas hijas?");
	strcpy(unJuego->descripcionRespuesta, "4. Fotosintesis");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la funcion principal de los globulos rojos?");
	strcpy(unJuego->descripcionRespuesta, "1. Combatir enfermedades");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la funcion principal de los globulos rojos?");
	strcpy(unJuego->descripcionRespuesta, "2. Coagular la sangre");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la funcion principal de los globulos rojos?");
	strcpy(unJuego->descripcionRespuesta, "3. Llevar oxigeno");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la funcion principal de los globulos rojos?");
	strcpy(unJuego->descripcionRespuesta, "4. Producir anticuerpos");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la velocidad a la que viaja la luz?");
	strcpy(unJuego->descripcionRespuesta, "1. 300.000m/s");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la velocidad a la que viaja la luz?");
	strcpy(unJuego->descripcionRespuesta, "2. 300.000km/s");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la velocidad a la que viaja la luz?");
	strcpy(unJuego->descripcionRespuesta, "3. 30.000km/h");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la velocidad a la que viaja la luz?");
	strcpy(unJuego->descripcionRespuesta, "4. 300.00km/h");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la fuerza fisica que la Tierra ejerce sobre los cuerpos hacia su centro?");
	strcpy(unJuego->descripcionRespuesta, "1. Gravedad");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la fuerza fisica que la Tierra ejerce sobre los cuerpos hacia su centro?");
	strcpy(unJuego->descripcionRespuesta, "2. Normal");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la fuerza fisica que la Tierra ejerce sobre los cuerpos hacia su centro?");
	strcpy(unJuego->descripcionRespuesta, "3. Rozamiento");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Cual es la fuerza fisica que la Tierra ejerce sobre los cuerpos hacia su centro?");
	strcpy(unJuego->descripcionRespuesta, "4. Atraccion");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Donde se localiza la informacion genetica en las celulas?");
	strcpy(unJuego->descripcionRespuesta, "1. En el nucleo");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Donde se localiza la informacion genetica en las celulas?");
	strcpy(unJuego->descripcionRespuesta, "2. En la membrana");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Donde se localiza la informacion genetica en las celulas?");
	strcpy(unJuego->descripcionRespuesta, "3. En el citoplasma");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Donde se localiza la informacion genetica en las celulas?");
	strcpy(unJuego->descripcionRespuesta, "4. Ribosoma");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Como se llaman las particulas subatomicas con carga electrica negativa?");
	strcpy(unJuego->descripcionRespuesta, "1. Neutrones");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Como se llaman las particulas subatomicas con carga electrica negativa?");
	strcpy(unJuego->descripcionRespuesta, "2. Protones");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Como se llaman las particulas subatomicas con carga electrica negativa?");
	strcpy(unJuego->descripcionRespuesta, "3. Electrones");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	strcpy(unJuego->descripcionPregunta, "Como se llaman las particulas subatomicas con carga electrica negativa?");
	strcpy(unJuego->descripcionRespuesta, "4. Atomos");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 5;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Quien realiza la voz de El Burro en la pelicula de Shrek?");
	strcpy(unJuego->descripcionRespuesta, "1. Eddie Murphy");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Quien realiza la voz de El Burro en la pelicula de Shrek?");
	strcpy(unJuego->descripcionRespuesta, "2. Cody Cameron");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Quien realiza la voz de El Burro en la pelicula de Shrek?");
	strcpy(unJuego->descripcionRespuesta, "3. Antonio Banderas");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Quien realiza la voz de El Burro en la pelicula de Shrek?");
	strcpy(unJuego->descripcionRespuesta, "4. Conrad Vernon");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 1;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cual banda armo Paul McCartney luego de la separacion de The Beatles?");
	strcpy(unJuego->descripcionRespuesta, "1. Plastic Ono Band");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cual banda armo Paul McCartney luego de la separacion de The Beatles?");
	strcpy(unJuego->descripcionRespuesta, "2. The Quarrymen");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cual banda armo Paul McCartney luego de la separacion de The Beatles?");
	strcpy(unJuego->descripcionRespuesta, "3. The Silver Beetles");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cual banda armo Paul McCartney luego de la separacion de The Beatles?");
	strcpy(unJuego->descripcionRespuesta, "4. Wings");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 2;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Con cual pelicula gano el Oscar al mejor actor Leonardo DiCaprio?");
	strcpy(unJuego->descripcionRespuesta, "1. Diamante de sangre");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Con cual pelicula gano el Oscar al mejor actor Leonardo DiCaprio?");
	strcpy(unJuego->descripcionRespuesta, "2. Titanic");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Con cual pelicula gano el Oscar al mejor actor Leonardo DiCaprio?");
	strcpy(unJuego->descripcionRespuesta, "3. El lobo de Wall Street");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Con cual pelicula gano el Oscar al mejor actor Leonardo DiCaprio?");
	strcpy(unJuego->descripcionRespuesta, "4. El renacido");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 3;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Como se llama la cuarta pelicula de la saga de Harry Potter?");
	strcpy(unJuego->descripcionRespuesta, "1. La orden del Fenix");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Como se llama la cuarta pelicula de la saga de Harry Potter?");
	strcpy(unJuego->descripcionRespuesta, "2. El caliz de fuego");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Como se llama la cuarta pelicula de la saga de Harry Potter?");
	strcpy(unJuego->descripcionRespuesta, "3. La camara secreta");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Como se llama la cuarta pelicula de la saga de Harry Potter?");
	strcpy(unJuego->descripcionRespuesta, "4. El Principe Mestizo");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 4;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cuantas temporadas tiene la serie Friends?");
	strcpy(unJuego->descripcionRespuesta, "1. 10");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cuantas temporadas tiene la serie Friends?");
	strcpy(unJuego->descripcionRespuesta, "2. 15");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cuantas temporadas tiene la serie Friends?");
	strcpy(unJuego->descripcionRespuesta, "3. 12");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cuantas temporadas tiene la serie Friends?");
	strcpy(unJuego->descripcionRespuesta, "4. 20");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 5;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cual es el apellido de Apu en Los Simpsons?");
	strcpy(unJuego->descripcionRespuesta, "1. Nahasapasapetilon");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 1;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cual es el apellido de Apu en Los Simpsons?");
	strcpy(unJuego->descripcionRespuesta, "2. Narahasapetilon");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 2;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cual es el apellido de Apu en Los Simpsons?");
	strcpy(unJuego->descripcionRespuesta, "3. Nahasapeemapetilon");
	unJuego->esCorrecta = true;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 3;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	strcpy(unJuego->descripcionPregunta, "Cual es el apellido de Apu en Los Simpsons?");
	strcpy(unJuego->descripcionRespuesta, "4. Nahasaapematilon");
	unJuego->esCorrecta = false;
	unJuego->idCategoria = 6;
	unJuego->idPregunta = 6;
	unJuego->idRespuesta = 4;
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	
	fclose(archivoContenido);
	
	/*strcpy(unJuego->nombreCategoria, "Geografia");
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Deportes");
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Arte");
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Ciencia");
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);
	strcpy(unJuego->nombreCategoria, "Entretenimiento");
	fwrite(unJuego, sizeof(Juego), 1, archivoContenido);*/
	
	/*while (fread(unJuego, sizeof(Juego), 1, archivoContenido))
	{
		cout<<unJuego->nombreCategoria;
	}*/
	

	
// ====== LOGICA DE TURNOS Y RONDAS DURANTE EL JUEGO =======
	/*ListaParticipantes* participantesEnJuego =  ingresarParticipantes();
   	ListaRondas* rondasIniciales = generarRondas(5,participantesEnJuego);
	NodoRonda* rondaAuxiliar = rondasIniciales->primerElemento;

	// ========== Empiezo a recorrer las rondas =========
	while(rondaAuxiliar != NULL){
		NodoTurno* turnoAuxiliar = rondaAuxiliar->turnos->primerElemento;
		// ======== Empiezo a recorrer los turnos de cada ronda ======
		while(turnoAuxiliar != NULL){
			Respuesta respuestaJugador = new Respuesta();
			Participante participanteActual = turnoAuxiliar->turno->participante;


			cout << "Es el turno de " << participanteActual->nombre;
			cout << turnoAuxiliar->unaPregunta->descripcion << endl;


			for (int i = 0; i < 4; ++i)
			{
				
				cout << turnoAuxiliar->unaPregunta->respuestas[i]->descripcion<<endl; 
			}
			cout << "Elija su respuesta." << endl;
			int nroRespuesta = NULL;
			cin >> nroRespuesta;
			while(nroRespuesta != 0 && nroRespuesta != 1 && nroRespuesta != 2 && nroRespuesta != 3){
				cout << "Respuesta invÃ¡lida. Ingrese su respuesta nuevamente." << endl;
				cin >> nroRespuesta;
			}
			respuestaJugador = turnoAuxiliar->unaPregunta->respuestas[nroRespuesta];
			turnoAuxiliar->unaRespuesta = respuestaJugador; 

			if (respuestaJugador->correcta == 1) 
			{	
				cout << "Â¡Respuesta Correcta!" << endl;
				participanteActual->puntos = puntos + 1;
			} else {
				cout << "Respuesta Incorrecta" << endl;
			}
			
			NodoParticipante* participanteAuxiliar = participantesEnJuego->primerElemento;
			while(participanteAuxiliar != NULL){
				unParticipante = participanteAuxiliar->participante;
				cout << "Participante: " << unParticipante->nombre << endl;
				cout << "Puntos: " << unParticipante->puntos << endl;

				participanteAuxiliar = participanteAuxiliar->siguienteElemento;
			}

			// ============= Opciones Turno ==============

			opcionesTurno(participanteActual, rondasIniciales);

			turnoAuxiliar = turnoAuxiliar->siguienteElemento;

		}

		rondaAuxiliar = rondaAuxiliar->siguienteElemento;
	}*/
	return 0;
}

/* void iniciarCategoriasPreguntasRespuestas(ListaCategoria* categorias){
	//Abro archivo
	int index = 1;
	while (index < 100) {
		//CategoriaToRead cat  = fread(sizeof(CategoriaToRead))
		Categoria* unaCategoria = categoriaCreate(cat);
		//
		index++;
	}
}*/
